# Don't trigger the pipline if only one of these files has changed
.fileignore_template: &CI_Ignore
  except:
    changes:
      - "*.md"
      - appveyor.yml
      - .travis.yml
      - .circleci/*
      - .github/*
      - scripts/*
      - images/*
      - data_files/*
      - docs/*

# Generic commands for building
.build__template: &Build
  - cmake --build ./build

# Generic commands for moving to the build directory and running tests
.run_test_template: &RunTests
  - cd build
  - ctest -j2 -V

# Which packages are required for GCC compilation
.gcc_install_template: &GCCPackages
  - apt -y install gcc g++ gcc-$GCC_VERSION g++-$GCC_VERSION

# Which pacakges are required for clang compilation
.clang_install_template: &ClangPackages
  - apt -y install clang clang-8 libstdc++-8-dev

# Configuration steps to inherit from
.configure_template:
  stage: configure
  <<: *CI_Ignore
  tags:
    - linux
  artifacts:
    paths:
      - build

# Build steps to inherit from
.build_template:
  stage: build
  <<: *CI_Ignore
  tags:
    - linux
  artifacts:
    paths:
      - build

# Test steps to inherit form
.test_template:
  stage: test
  <<: *CI_Ignore
  tags:
    - linux

# Specify "rolling" rather than "latest"
# We need gcc >=8 and clang >=7 for std::filesystem
image: ubuntu:rolling

# List the stages to be run
stages:
  - configure
  - build
  - test

# Install common packages for all stages
before_script:
  - apt update && apt -y install cmake ninja-build

# Make sure the submodules are pulled in
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GCC_VERSION: 8

# GCC - Debug
gcc-configure-Debug:
  extends: .configure_template
  script:
    - *GCCPackages
    - cmake -H. -B./build -GNinja -DINCH_UNIT_TESTS=ON -DCMAKE_CXX_COMPILER=/usr/bin/g++-$GCC_VERSION -DCMAKE_BUILD_TYPE=Debug

gcc-build-Debug:
  extends: .build_template
  script:
    - *GCCPackages
    - *Build
  dependencies:
    - gcc-configure-Debug

gcc-test-Debug:
  extends: .test_template
  script:
    - *GCCPackages
    - *RunTests
  dependencies:
    - gcc-build-Debug

# GCC - Release
gcc-configure-Release:
  extends: .configure_template
  script:
    - *GCCPackages
    - cmake -H. -B./build -GNinja -DINCH_UNIT_TESTS=ON -DCMAKE_CXX_COMPILER=/usr/bin/g++-$GCC_VERSION -DCMAKE_BUILD_TYPE=Release

gcc-build-Release:
  extends: .build_template
  script:
    - *GCCPackages
    - *Build
  dependencies:
    - gcc-configure-Release

gcc-test-Release:
  extends: .test_template
  script:
    - *GCCPackages
    - *RunTests
  dependencies:
    - gcc-build-Release



#gcc-build-Release:
#  stage: gcc-build
#  <<: *CI_Ignore
#  tags:
#    - linux
#  script:
#    - apt -y install gcc g++ gcc-8 g++-8
#    - cmake -H. -B../build -GNinja -DINCH_UNIT_TESTS=ON -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DCMAKE_BUILD_TYPE=Release
#    - *Build_n_Test
#
## clang/LLVM
#clang-build-Debug:
#  stage: clang-build
#  <<: *CI_Ignore
#  tags:
#    - linux
#  script:
#    - apt -y install clang clang-8 libstdc++-8-dev
#    - cmake -H. -B../build -GNinja -DINCH_UNIT_TESTS=ON -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_BUILD_TYPE=Debug
#    - *Build_n_Test
#
#clang-build-Release:
#  stage: clang-build
#  <<: *CI_Ignore
#  tags:
#    - linux
#  script:
#    - apt -y install clang clang-8 libstdc++-8-dev
#    - cmake -H. -B../build -GNinja -DINCH_UNIT_TESTS=ON -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_BUILD_TYPE=Release
#    - *Build_n_Test
