stages:
  - gcc-build

image: gcc:8

before_script:
  - apt update && apt -y install cmake ninja-build

gcc-build-Debug:
  stage: gcc-build

  script:
    - mkdir ../build && cd $_
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ../$CI_PROJECT_NAME && cmake --build .

gcc-build-Release:
  stage: gcc-build

  script:
    - mkdir ../build && cd $_
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ../$CI_PROJECT_NAME && cmake --build .
