stages:
  - gcc-build
  - clang-build

#Full ubuntu image seems a bit heavy handed
#There is an offical gcc image, but not clang/llvm
image: ubuntu:latest

#Install the required packages to run the jobs
before_script:
  - apt update && apt -y install cmake ninja-build

# GCC
gcc-build-Debug:
  stage: gcc-build

  script:
    - apt -y install g++
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_BUILD_TYPE=Debug
    - cmake --build ../build

gcc-build-Release:
  stage: gcc-build

  script:
    - apt -y install g++
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release
    - cmake --build ../build

# clang/LLVM
clang-build-Debug:
  stage: clang-build

  script:
    - apt -y install clang
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_BUILD_TYPE=Debug
    - cmake --build ../build

clang-build-Release:
  stage: clang-build

  script:
    - apt -y install clang
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_BUILD_TYPE=Release
    - cmake --build ../build
