stages:
  - gcc-build

image: gcc:8

gcc-build-Debug:
  stage: gcc-build

  before_script:
    - apt update && apt -y install cmake ninja-build

  script:
    - mkdir ../build && cd ../build
    - cmake -DCMAKE_BUILD_TYPE=Debug ../$CI_PROJECT_NAME && cmake --build .

gcc-build-Release:
  stage: gcc-build

  before_script:
    - apt update && apt -y install cmake ninja-build

  script:
    - mkdir ../build && cd ../build
    - cmake -DCMAKE_BUILD_TYPE=Release ../$CI_PROJECT_NAME && cmake --build .
