stages:
  - gcc-build
  - clang-build

# Specify "bionic" rather than "latest"
# We need gcc >=8 and clang >=7 for std::filesystem
image: ubuntu:eoan

#Install the required packages to run the jobs of all stages
before_script:
  - apt update && apt -y install cmake ninja-build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# GCC
gcc-build-Debug:
  stage: gcc-build
  except:
    changes:
        - "*.md"
        - appveyor.yml
        - .travis.yml
        - .circleci/*
        - .github/*
        - scripts/*
        - images/*
        - data_files/*
        - docs/*

  script:
    - apt -y install gcc g++ gcc-8 g++-8
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DCMAKE_BUILD_TYPE=Debug
    - cmake --build ../build
    - cd ../build
    - ctest -V

gcc-build-Release:
  stage: gcc-build
  except:
    changes:
        - "*.md"
        - appveyor.yml
        - .travis.yml
        - .circleci/*
        - .github/*
        - scripts/*
        - images/*
        - data_files/*
        - docs/*

  script:
    - apt -y install gcc g++ gcc-8 g++-8
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DCMAKE_BUILD_TYPE=Release
    - cmake --build ../build
    - cd ../build
    - ctest -V

# clang/LLVM
clang-build-Debug:
  stage: clang-build
  except:
    changes:
        - "*.md"
        - appveyor.yml
        - .travis.yml
        - .circleci/*
        - .github/*
        - scripts/*
        - images/*
        - data_files/*
        - docs/*

  script:
    - apt -y install clang clang-8 libstdc++-8-dev
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_BUILD_TYPE=Debug
    - cmake --build ../build
    - cd ../build
    - ctest -V

clang-build-Release:
  stage: clang-build
  except:
    changes:
        - "*.md"
        - appveyor.yml
        - .travis.yml
        - .circleci/*
        - .github/*
        - scripts/*
        - images/*
        - data_files/*
        - docs/*

  script:
    - apt -y install clang clang-8 libstdc++-8-dev
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_BUILD_TYPE=Release
    - cmake --build ../build
    - cd ../build
    - ctest -V
