stages:
  - gcc-build
  - clang-build

# Specify "bionic" rather than "latest"
# We need gcc >=8 and clang >=7 for std::filesystem
image: ubuntu:bionic

#Install the required packages to run the jobs of all stages
before_script:
  - apt update && apt -y install cmake ninja-build

# GCC
gcc-build-Debug:
  stage: gcc-build

  script:
    - apt -y install gcc g++ gcc-8 g++-8
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DCMAKE_BUILD_TYPE=Debug
    - cmake --build ../build
    - cd ../build
    - ctest -V

gcc-build-Release:
  stage: gcc-build

  script:
    - apt -y install gcc g++ gcc-8 g++-8
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DCMAKE_BUILD_TYPE=Release
    - cmake --build ../build
    - cd ../build
    - ctest -V

# clang/LLVM
clang-build-Debug:
  stage: clang-build

  script:
    - apt -y install clang clang-7
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/clang++-7 -DCMAKE_BUILD_TYPE=Debug
    - cmake --build ../build
    - cd ../build
    - ctest -V

clang-build-Release:
  stage: clang-build

  script:
    - apt -y install clang clang-7
    - cmake -H. -B../build -GNinja -DCMAKE_CXX_COMPILER=/usr/bin/clang++-7 -DCMAKE_BUILD_TYPE=Release
    - cmake --build ../build
    - cd ../build
    - ctest -V
