version: 2.0
jobs:
  build_gcc_debug:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      -run:
        name: "Pull Submodules"
        command: |
          git submodule init
          git submodule update --remote
      - run: apt update && apt install -y cmake ninja-build gcc g++ gcc-8 g++-8
      - run: cmake -GNinja -H. -B../Debug-build -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build ../Debug-build
      - run: cd ../Debug-build && ctest -V

  build_gcc_release:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      -run:
        name: "Pull Submodules"
        command: |
          git submodule init
          git submodule update --remote
      - run: apt update && apt install -y cmake ninja-build gcc g++ gcc-8 g++-8
      - run: cmake -GNinja -H. -B../Release-build -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build ../Release-build
      - run: cd ../Release-build && ctest -V

  build_clang_debug:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      -run:
        name: "Pull Submodules"
        command: |
          git submodule init
          git submodule update --remote
      - run: apt update && apt install -y cmake ninja-build clang clang-8 libstdc++-8-dev
      - run: cmake -GNinja -H. -B../Debug-build -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build ../Debug-build
      - run: cd ../Debug-build && ctest -V

  build_clang_release:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      -run:
        name: "Pull Submodules"
        command: |
          git submodule init
          git submodule update --remote
      - run: apt update && apt install -y cmake ninja-build clang clang-8 libstdc++-8-dev
      - run: cmake -GNinja -H. -B../Release-build -DCMAKE_CXX_COMPILER=/usr/bin/clang++-8 -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build ../Release-build
      - run: cd ../Release-build && ctest -V

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_debug
      - build_gcc_release
      - build_clang_debug
      - build_clang_release
