version: 2.0
jobs:
  build_gcc:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: apt update && apt install -y cmake ninja-build gcc g++
      - run: cmake -GNinja -H. -B../Debug-build -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build ../Debug-build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc
